resolver: lts-3.4
packages:
  - serversession
  - serversession-backend-acid-state
  - serversession-backend-persistent
  - serversession-backend-redis
  - serversession-frontend-snap
  - serversession-frontend-wai
  - serversession-frontend-yesod
extra-deps:
  - acid-state-0.13.0
  - nonce-1.0.2
  - wai-session-0.3.2
