Default: &defaults
  database: serversession-example-yesod-persistent.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: serversession-example-yesod-persistent_test.sqlite3
  <<: *defaults

Staging:
  database: serversession-example-yesod-persistent_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: serversession-example-yesod-persistent_production.sqlite3
  poolsize: 100
  <<: *defaults
